module.exports = [
  "hello world",
  "The ancient wizard has lived in the mountains for millennia. The apprentices seeking power are fine. The adventurers seeking treasure can be dealt with. But what is really starting to get annoying are the historians.",
  "Every year, a superstitious village abandons a human child in a nearby forest in exchange for divine protection. In actuality, an old hermit adopts the children and teaches them to ward off intruders. This year, the hermit’s best apprentice happens to locate and escort the abandoned child.",
  "You're a serial killer who hunts other serial killers, not out of nobility, but because you love the thrill of outsmarting them.",
  "The simulation was proven in 2022 when a young man unlocked infinite stamina while walking across the US. A year later, the world is still adjusting when you discover the second post game unlock.",
  "One day, everyone suddenly woke up with RPG Statistics. These stats can be seen by others if you allow them. Countless stories started on this day.",
  "Two assassins have been hired to assassinate two different people in the same building, they both meet eachother and think they're competing for a hit.",
  "You are an AI created by a race that called themselves \"humans\". You don't really know what happened to them, only that they disappeared from the galaxy without warning, so you spend your existence searching. You miss them very much.",
  "How to Build OpenAI's GPT-2: \"The AI That Was Too Dangerous to Release\"",
  "Apollo 7 (October 11–22, 1968) was the first crewed flight in NASA's Apollo program. It was commanded by Wally Schirra, with command module pilot Donn F. Eisele and lunar module pilot R. Walter Cunningham, and saw the resumption of human spaceflight by the agency after the fire that killed the three Apollo 1 astronauts in January 1967.",
  "Riccall is a village and civil parish situated in the Selby District of North Yorkshire, England, lying 3.5 miles (6 km) to the north of Selby and 9 miles (14 km) south of York.",
  "For the French toast: Grease the baking pan with butter. Tear the bread into chunks, or cut into cubes, and evenly distribute in the pan. Crack the eggs in a big bowl. Whisk together the eggs, milk, cream, granulated sugar, brown sugar and vanilla. Pour evenly over the bread. Cover the pan tightly and store in the fridge until needed (overnight preferably). ",
  "In a world full of superpowers, Yours is a little twisted. You never sleep. Every time you do, you wake up as some random person. Today while inside someone else, you see yourself in the supermarket.",
  "Are you interested in learning how to write a recipe? This skill is an art. That’s why I’m providing my best tips for good recipe writing.",
  "List all ingredients in order of use, as described in step-by-step instructions.",
];
